#pragma config(Sensor, S3,     colour,         sensorEV3_Color)
#pragma config(Motor,  motorB,          leftWheel,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightWheel,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int current;

task scanCurrent(){
	while(true){
		current = SensorValue[colour];
	}
}


bool sense(int black){
		if(current < black + 10 && current > black-10){
				playSound(soundBlip);
				return true;
		}
		return false;
}


void started(int black, bool passedTile){
	displayCenteredBigTextLine(1, "Here! ");

	while(true){
		motor[leftWheel] = 10;
		motor[rightWheel] = 10;

		if(current > black + 10){
			passedTile = true;
		}

		if(current > black-10 && current < black +10 && passedTile == true){
				setMotorTarget(leftWheel, 500, 20);
				motor[rightWheel] = 0;
				return;
		}
	}
}

void tower(int black, bool passedTile){
			int tileNum = 0;

			//turn 90 degrees right
			setMotorTarget(leftWheel, 500, 20);
			motor[rightWheel] = 0;
			
			displayCenteredBigTextLine(4, "Backwards ");
			wait1MSec(2000);
			

			setMotorTarget(leftWheel, 360, 20);
			setMotorTarget(rightWheel, 360, 20);
			int grey = current;

			while(tileNum < 3){
				//detect other than grey
				if(current > grey + 5 || current < grey - 10){
					passedTile = true;
				}

				if(passedTile == true && current < grey + 5 && current > grey - 10){
					tileNum++;
					passedTile = false;
				}
			}
}

task main(){
//Move in straight line, count 15 black tiles, sound at each black tile, then stop

  int black = SensorValue[colour];
	int count=1;
	bool passedTile = false;

	startTask(scanCurrent);
	started(black, passedTile);
	wait1Msec(3000);

	while(count < 15){
	//	displayCenteredBigTextLine(1, "Count is %d", count);

		if(current > black + 10){
			passedTile = true;
		}

		motor[leftWheel] = 20;
		motor[rightWheel] = 20;

	  if(passedTile == true && sense(black)){
	  	count++;
	  	passedTile = false;
	  }
	}


	motor[leftWheel] = 0;
	motor[rightWheel] = 0;
	displayCenteredBigTextLine(4, "DONE! %d", count);

	tower(black, passedTile);
}
